// <auto-generated />
using BackendAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendAPI.Migrations
{
    [DbContext(typeof(BackendAPIContext))]
    [Migration("20230603115734_15")]
    partial class _15
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BackendAPI.Models.Food", b =>
                {
                    b.Property<int>("FoodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodID"), 1L, 1);

                    b.Property<string>("FoodDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendorID")
                        .HasColumnType("int");

                    b.HasKey("FoodID");

                    b.ToTable("Food");

                    b.HasData(
                        new
                        {
                            FoodID = 1,
                            FoodDescription = "Modi praesentium reiciendis veritatis est iusto ratione dolore.",
                            FoodName = "Aspestos Flavoured sausages",
                            FoodType = "Cake",
                            VendorID = 2
                        },
                        new
                        {
                            FoodID = 2,
                            FoodDescription = "Exercitationem quia doloribus et ea et quidem voluptatum.",
                            FoodName = "Bacon Flavoured Icecream",
                            FoodType = "Burger",
                            VendorID = 1
                        },
                        new
                        {
                            FoodID = 3,
                            FoodDescription = "Rem et dolore omnis consequatur accusamus.",
                            FoodName = "Mac and Cheese Filled Doughnuts",
                            FoodType = "Cupcake",
                            VendorID = 1
                        },
                        new
                        {
                            FoodID = 4,
                            FoodDescription = "Quos blanditiis officiis voluptatem odio non iusto dolor.",
                            FoodName = "frostly Flakes Flavoured Milk",
                            FoodType = "Cupcake",
                            VendorID = 1
                        },
                        new
                        {
                            FoodID = 5,
                            FoodDescription = "Magni necessitatibus qui atque temporibus placeat in.",
                            FoodName = "Plastic Cheese Burger",
                            FoodType = "Snack",
                            VendorID = 1
                        },
                        new
                        {
                            FoodID = 6,
                            FoodDescription = "Maiores culpa consequatur totam cupiditate recusandae.",
                            FoodName = "Apple pie arsenic surpise",
                            FoodType = "Cake",
                            VendorID = 2
                        },
                        new
                        {
                            FoodID = 7,
                            FoodDescription = "Aut rem deserunt fugit quisquam non.",
                            FoodName = "A Warm Apple pie",
                            FoodType = "Cupcake",
                            VendorID = 2
                        },
                        new
                        {
                            FoodID = 8,
                            FoodDescription = "Ab architecto iste vero rerum voluptatem.",
                            FoodName = "Cardboard Pizza",
                            FoodType = "Snack",
                            VendorID = 1
                        },
                        new
                        {
                            FoodID = 9,
                            FoodDescription = "Non qui aut quia enim eligendi et fugiat quasi et.",
                            FoodName = "Chocolate Cake",
                            FoodType = "Beverage",
                            VendorID = 1
                        },
                        new
                        {
                            FoodID = 10,
                            FoodDescription = "Et ea aliquid omnis placeat.",
                            FoodName = "Live Plus Energy Drink",
                            FoodType = "Burger",
                            VendorID = 2
                        },
                        new
                        {
                            FoodID = 11,
                            FoodDescription = "Aut voluptas ad laboriosam iure in.",
                            FoodName = "Oliver's Favorite Food",
                            FoodType = "Beverage",
                            VendorID = 2
                        });
                });

            modelBuilder.Entity("BackendAPI.Models.Furniture", b =>
                {
                    b.Property<int>("furnitureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("furnitureID"), 1L, 1);

                    b.Property<int>("VendorID")
                        .HasColumnType("int");

                    b.Property<string>("furnitureDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("furnitureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("furnitureType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("furnitureID");

                    b.ToTable("Furniture");

                    b.HasData(
                        new
                        {
                            furnitureID = 1,
                            VendorID = 1,
                            furnitureDescription = "In dignissimos id.",
                            furnitureName = "Thrustmaster 1000",
                            furnitureType = "Occasional Furniture"
                        },
                        new
                        {
                            furnitureID = 2,
                            VendorID = 2,
                            furnitureDescription = "Et repudiandae voluptatem sit odio aut laboriosam.",
                            furnitureName = "The Pull Out",
                            furnitureType = "Couch"
                        },
                        new
                        {
                            furnitureID = 3,
                            VendorID = 2,
                            furnitureDescription = "Sed iure omnis quibusdam.",
                            furnitureName = "The waterbed",
                            furnitureType = "Occasional Furniture"
                        },
                        new
                        {
                            furnitureID = 4,
                            VendorID = 1,
                            furnitureDescription = "Et placeat minima et dolor et.",
                            furnitureName = "regretabed",
                            furnitureType = "Couch"
                        });
                });

            modelBuilder.Entity("BackendAPI.Models.Vehicle", b =>
                {
                    b.Property<int>("vehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vehicleID"), 1L, 1);

                    b.Property<int>("VendorID")
                        .HasColumnType("int");

                    b.Property<string>("vehicleDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vehicleID");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            vehicleID = 1,
                            VendorID = 2,
                            vehicleDescription = "Eaque facilis omnis sed dolorum. Eveniet reiciendis explicabo earum omnis minus. Fuga reprehenderit tempora sapiente itaque sequi nihil accusamus. Fuga sunt rem aut est eos molestiae et. Aliquid dicta praesentium placeat. Maxime ratione harum deleniti.",
                            vehicleName = "Honda Del Sol",
                            vehicleType = "Sedan"
                        },
                        new
                        {
                            vehicleID = 2,
                            VendorID = 1,
                            vehicleDescription = "Sed dolores consequuntur quia fugiat distinctio. Ut quia voluptatem. Similique aut in libero facere. Dicta at est. Non autem debitis aliquid est nam cupiditate laboriosam magnam.",
                            vehicleName = "Honda Accord",
                            vehicleType = "Ute"
                        },
                        new
                        {
                            vehicleID = 3,
                            VendorID = 2,
                            vehicleDescription = "Expedita voluptates natus ad vel sed sed earum nemo voluptatem. Corrupti ex nobis optio perspiciatis et dolorem. Rerum quasi ipsa occaecati incidunt distinctio laboriosam. Ipsam repellendus repellendus suscipit nesciunt sint ut in consequatur. Est nihil quia. Ut vel nobis iste eum fugiat.",
                            vehicleName = "Holden Crewman  S",
                            vehicleType = "Sedan"
                        },
                        new
                        {
                            vehicleID = 4,
                            VendorID = 1,
                            vehicleDescription = "Eos ipsum voluptatem ullam nihil aut aliquid voluptatem. Qui numquam quia repellendus. Est et eum et consequatur in dolore.",
                            vehicleName = "Holden Crewman SS",
                            vehicleType = "StationWagon"
                        },
                        new
                        {
                            vehicleID = 5,
                            VendorID = 1,
                            vehicleDescription = "Ratione non ipsum. Molestiae ut voluptates vel voluptatem quibusdam. Tempore illo architecto et voluptas ut voluptatem aut delectus similique. Officiis esse sunt aut minus molestiae sed quasi. Voluptatem voluptates possimus harum in.",
                            vehicleName = "Nissan Tiida Latio",
                            vehicleType = "Sedan"
                        },
                        new
                        {
                            vehicleID = 6,
                            VendorID = 1,
                            vehicleDescription = "Dolor minus laboriosam consectetur voluptas ut qui molestiae. Sit accusamus corrupti repudiandae consequatur fuga at sit ut eum. Ipsum animi animi tempora. Mollitia est sit dolores ducimus nisi quia.",
                            vehicleName = "Mazda Verisa",
                            vehicleType = "Ute"
                        },
                        new
                        {
                            vehicleID = 7,
                            VendorID = 1,
                            vehicleDescription = "Nobis hic odit ut dolores in sapiente. Esse aut delectus est ex. Et autem et qui officiis quibusdam ullam. Aspernatur quia dolores porro quasi optio.",
                            vehicleName = "Ford Falcon FG XR6",
                            vehicleType = "Ute"
                        },
                        new
                        {
                            vehicleID = 8,
                            VendorID = 2,
                            vehicleDescription = "Eum sed dicta similique aut. Dicta quis est ipsum quidem ducimus consequatur. Qui voluptatem tempora consequatur ad aut provident. Porro quam error. Iure quo est nulla. Officia dolores aut et dolorem qui officia quasi maxime et.",
                            vehicleName = "Ford Falcon BA XR8",
                            vehicleType = "Shitbox"
                        },
                        new
                        {
                            vehicleID = 9,
                            VendorID = 1,
                            vehicleDescription = "Suscipit facilis repellat in in. Unde aut sed aut cumque. Aut quibusdam ullam quis. Velit dolores qui. Est similique aliquid officia.",
                            vehicleName = "Nissan Cefiro",
                            vehicleType = "Shitbox"
                        },
                        new
                        {
                            vehicleID = 10,
                            VendorID = 1,
                            vehicleDescription = "Pariatur ut culpa laborum odit qui. Recusandae rerum veniam possimus. Enim accusantium porro et nihil officia. Modi accusamus quibusdam suscipit nisi earum quas ullam fuga.",
                            vehicleName = "Nissan Stagea",
                            vehicleType = "HatchBack"
                        },
                        new
                        {
                            vehicleID = 11,
                            VendorID = 1,
                            vehicleDescription = "Aspernatur nisi est. Ipsam vero culpa. Repellat esse minima. Qui quia maiores natus.",
                            vehicleName = "Subaru WRX",
                            vehicleType = "StationWagon"
                        });
                });

            modelBuilder.Entity("BackendAPI.Models.Vendor", b =>
                {
                    b.Property<int>("VendorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendorID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VendorID");

                    b.ToTable("Vendor");

                    b.HasData(
                        new
                        {
                            VendorID = 1,
                            Description = "Libero quis et laborum vel reprehenderit vero.",
                            Location = "67063 Delbert Grove",
                            Name = "Kronos Incoporated"
                        },
                        new
                        {
                            VendorID = 2,
                            Description = "Esse voluptatem dolores sed aut voluptates et.",
                            Location = "823 Thiel Ranch",
                            Name = "Kronos Incoporated"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
