// <auto-generated />
using BackendAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendAPI.Migrations
{
    [DbContext(typeof(BackendAPIContext))]
    partial class BackendAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BackendAPI.Models.Food", b =>
                {
                    b.Property<int>("FoodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodID"), 1L, 1);

                    b.Property<string>("FoodDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendorID")
                        .HasColumnType("int");

                    b.HasKey("FoodID");

                    b.ToTable("Food");

                    b.HasData(
                        new
                        {
                            FoodID = 1,
                            FoodDescription = "Culpa possimus sed molestiae.",
                            FoodName = "Aspestos Flavoured sausages",
                            FoodType = "Muffin",
                            VendorID = 2
                        },
                        new
                        {
                            FoodID = 2,
                            FoodDescription = "Velit non quisquam quia.",
                            FoodName = "Bacon Flavoured Icecream",
                            FoodType = "Snack",
                            VendorID = 1
                        },
                        new
                        {
                            FoodID = 3,
                            FoodDescription = "Ullam consequatur deleniti qui placeat ut ad.",
                            FoodName = "Mac and Cheese Filled Doughnuts",
                            FoodType = "Cupcake",
                            VendorID = 2
                        },
                        new
                        {
                            FoodID = 4,
                            FoodDescription = "Voluptates dolore et amet sunt aliquid et sequi.",
                            FoodName = "frostly Flakes Flavoured Milk",
                            FoodType = "Cake",
                            VendorID = 2
                        },
                        new
                        {
                            FoodID = 5,
                            FoodDescription = "Qui assumenda delectus recusandae est velit ipsam dignissimos temporibus.",
                            FoodName = "Plastic Cheese Burger",
                            FoodType = "Burger",
                            VendorID = 2
                        },
                        new
                        {
                            FoodID = 6,
                            FoodDescription = "Ipsum optio earum autem dicta cupiditate voluptatem qui suscipit.",
                            FoodName = "Apple pie arsenic surpise",
                            FoodType = "Cupcake",
                            VendorID = 1
                        },
                        new
                        {
                            FoodID = 7,
                            FoodDescription = "Quam voluptatem ullam sit.",
                            FoodName = "A Warm Apple pie",
                            FoodType = "Snack",
                            VendorID = 1
                        },
                        new
                        {
                            FoodID = 8,
                            FoodDescription = "Ut id ullam omnis recusandae tempore.",
                            FoodName = "Cardboard Pizza",
                            FoodType = "Burger",
                            VendorID = 1
                        },
                        new
                        {
                            FoodID = 9,
                            FoodDescription = "Sint voluptatem in ut quidem voluptas.",
                            FoodName = "Chocolate Cake",
                            FoodType = "Cupcake",
                            VendorID = 2
                        },
                        new
                        {
                            FoodID = 10,
                            FoodDescription = "Velit neque quia et temporibus rerum.",
                            FoodName = "Live Plus Energy Drink",
                            FoodType = "Snack",
                            VendorID = 2
                        },
                        new
                        {
                            FoodID = 11,
                            FoodDescription = "Provident iure qui quam voluptatem accusamus sint tempore fuga cum.",
                            FoodName = "Oliver's Favorite Food",
                            FoodType = "Muffin",
                            VendorID = 2
                        });
                });

            modelBuilder.Entity("BackendAPI.Models.Furniture", b =>
                {
                    b.Property<int>("furnitureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("furnitureID"), 1L, 1);

                    b.Property<int>("VendorID")
                        .HasColumnType("int");

                    b.Property<string>("furnitureDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("furnitureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("furnitureType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("furnitureID");

                    b.ToTable("Furniture");

                    b.HasData(
                        new
                        {
                            furnitureID = 1,
                            VendorID = 2,
                            furnitureDescription = "Nihil aspernatur cum.",
                            furnitureName = "Thrustmaster 1000",
                            furnitureType = "Occasional Furniture"
                        },
                        new
                        {
                            furnitureID = 2,
                            VendorID = 2,
                            furnitureDescription = "Quia sequi harum.",
                            furnitureName = "The Pull Out",
                            furnitureType = "Occasional Furniture"
                        },
                        new
                        {
                            furnitureID = 3,
                            VendorID = 2,
                            furnitureDescription = "Nesciunt nemo molestiae sapiente ut et labore.",
                            furnitureName = "The waterbed",
                            furnitureType = "Chair"
                        },
                        new
                        {
                            furnitureID = 4,
                            VendorID = 1,
                            furnitureDescription = "Illum dolor praesentium doloribus suscipit saepe.",
                            furnitureName = "regretabed",
                            furnitureType = "Occasional Furniture"
                        });
                });

            modelBuilder.Entity("BackendAPI.Models.Vehicle", b =>
                {
                    b.Property<int>("vehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vehicleID"), 1L, 1);

                    b.Property<int>("VendorID")
                        .HasColumnType("int");

                    b.Property<string>("vehicleDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vehicleID");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            vehicleID = 1,
                            VendorID = 1,
                            vehicleDescription = "Voluptates quos consequatur delectus quos maxime aliquam totam. Repudiandae esse unde pariatur ut. Qui voluptates reiciendis et. Sunt harum ullam iure et quo. Praesentium id veritatis minima eius ut maiores.",
                            vehicleName = "Honda Del Sol",
                            vehicleType = "Ute"
                        },
                        new
                        {
                            vehicleID = 2,
                            VendorID = 2,
                            vehicleDescription = "Neque voluptas enim libero magnam dolores. Voluptates repudiandae dicta ipsam blanditiis. Dolor rerum doloremque voluptates quia tenetur quae. Sequi eaque et voluptatem rem facilis dolores quam similique. Omnis sed mollitia numquam rerum totam qui similique ipsam voluptatem. Animi iste molestiae molestias.",
                            vehicleName = "Honda Accord",
                            vehicleType = "Ute"
                        },
                        new
                        {
                            vehicleID = 3,
                            VendorID = 2,
                            vehicleDescription = "Sit quo vel alias sit neque. Perferendis sit totam nam nesciunt sequi id laboriosam rerum. Et earum inventore non magnam corrupti dolores voluptate.",
                            vehicleName = "Holden Crewman  S",
                            vehicleType = "Shitbox"
                        },
                        new
                        {
                            vehicleID = 4,
                            VendorID = 2,
                            vehicleDescription = "Minus quia recusandae dolore magni amet nam eligendi necessitatibus dolor. Mollitia ad temporibus id nesciunt doloribus praesentium. Perspiciatis ea necessitatibus corporis itaque. Magnam molestiae impedit labore assumenda excepturi rerum. Repellat adipisci dolor. Fugiat similique et quam hic iure est ab rerum aperiam.",
                            vehicleName = "Holden Crewman SS",
                            vehicleType = "StationWagon"
                        },
                        new
                        {
                            vehicleID = 5,
                            VendorID = 2,
                            vehicleDescription = "Autem rerum enim architecto voluptas quas. Non similique magni architecto earum rerum at rerum iste. Dolorum enim aut nulla dignissimos assumenda ut alias aut. Esse et molestias laborum repellat nulla. Ullam quaerat sunt neque ut qui. Voluptas recusandae aut.",
                            vehicleName = "Nissan Tiida Latio",
                            vehicleType = "HatchBack"
                        },
                        new
                        {
                            vehicleID = 6,
                            VendorID = 1,
                            vehicleDescription = "Eum porro quia eius debitis enim et accusantium eum. Neque veniam dolorem temporibus labore vitae ut. Nobis et ad soluta mollitia assumenda deleniti alias sit.",
                            vehicleName = "Mazda Verisa",
                            vehicleType = "HatchBack"
                        },
                        new
                        {
                            vehicleID = 7,
                            VendorID = 1,
                            vehicleDescription = "Ipsa ipsa exercitationem nulla inventore. Et praesentium autem quis rem eveniet. Dignissimos nisi sed. Sint omnis hic. Officia eius aliquid veniam eos. Sunt eius et mollitia odio in dolor sed.",
                            vehicleName = "Ford Falcon FG XR6",
                            vehicleType = "Sedan"
                        },
                        new
                        {
                            vehicleID = 8,
                            VendorID = 1,
                            vehicleDescription = "Suscipit expedita incidunt nam. Laudantium vitae quidem expedita qui illo magnam. Asperiores eum culpa illum quae ex quos. Molestias provident cum officiis non. Ut nihil quis. Alias quam et repudiandae et doloremque qui placeat deleniti.",
                            vehicleName = "Ford Falcon BA XR8",
                            vehicleType = "HatchBack"
                        },
                        new
                        {
                            vehicleID = 9,
                            VendorID = 1,
                            vehicleDescription = "Ipsam itaque animi non sunt adipisci veniam voluptatibus ea. Deleniti ad nam quasi nisi molestiae natus dolor non saepe. Vel ut natus a suscipit sed et provident autem et. Itaque a assumenda vero et iusto blanditiis maiores animi eos. Ullam doloribus id cum vel.",
                            vehicleName = "Nissan Cefiro",
                            vehicleType = "Sedan"
                        },
                        new
                        {
                            vehicleID = 10,
                            VendorID = 2,
                            vehicleDescription = "Ea aspernatur nesciunt voluptatem. Accusantium magnam tempora asperiores molestias aut dolore. Cupiditate dolores voluptate officiis totam provident tempore rem repellendus et.",
                            vehicleName = "Nissan Stagea",
                            vehicleType = "HatchBack"
                        },
                        new
                        {
                            vehicleID = 11,
                            VendorID = 2,
                            vehicleDescription = "Nemo repudiandae quisquam veniam earum magni sunt aut dolorem voluptatem. Harum consequatur quia accusantium. Perspiciatis repellat esse quia consequatur debitis sit quis. Cupiditate id ut ex. Accusantium enim accusantium aliquid sed voluptatem et autem sunt praesentium. Temporibus consequatur et provident ea esse.",
                            vehicleName = "Subaru WRX",
                            vehicleType = "Ute"
                        });
                });

            modelBuilder.Entity("BackendAPI.Models.Vendor", b =>
                {
                    b.Property<int>("VendorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendorID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VendorID");

                    b.ToTable("Vendor");

                    b.HasData(
                        new
                        {
                            VendorID = 1,
                            Description = "Non voluptatem et saepe est ipsam molestiae consequatur qui enim.",
                            Location = "0744 Heathcote Stream",
                            Name = "Unlimited Problems Ltd."
                        },
                        new
                        {
                            VendorID = 2,
                            Description = "Nobis qui optio iure velit et saepe ut qui ipsam.",
                            Location = "0477 Weimann Parkway",
                            Name = "Underwhelming Results Agency"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
