// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(BackendContext))]
    [Migration("20230524104112_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Backend.Models.Food", b =>
                {
                    b.Property<int>("FoodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodID"), 1L, 1);

                    b.Property<string>("FoodDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendorID")
                        .HasColumnType("int");

                    b.HasKey("FoodID");

                    b.ToTable("Food");

                    b.HasData(
                        new
                        {
                            FoodID = 1,
                            FoodDescription = "Similique optio odit illum sint.",
                            FoodName = "frostly Flakes Flavoured Milk",
                            FoodType = "Breads",
                            VendorID = 2
                        },
                        new
                        {
                            FoodID = 2,
                            FoodDescription = "Sit quidem unde.",
                            FoodName = "Big Mac",
                            FoodType = "Breads",
                            VendorID = 2
                        },
                        new
                        {
                            FoodID = 3,
                            FoodDescription = "Temporibus eveniet sit explicabo.",
                            FoodName = "Chocolate Cake",
                            FoodType = "Breads",
                            VendorID = 1
                        },
                        new
                        {
                            FoodID = 4,
                            FoodDescription = "Quod vel ipsam quia.",
                            FoodName = "frostly Flakes Flavoured Milk",
                            FoodType = "Burger",
                            VendorID = 1
                        },
                        new
                        {
                            FoodID = 5,
                            FoodDescription = "Unde odit quia.",
                            FoodName = "Bacon Flavoured Icecream",
                            FoodType = "Snack",
                            VendorID = 2
                        },
                        new
                        {
                            FoodID = 6,
                            FoodDescription = "Sequi sed expedita adipisci sed placeat et nesciunt nulla.",
                            FoodName = "Mac and Cheese Filled Doughnuts",
                            FoodType = "Beverage",
                            VendorID = 2
                        },
                        new
                        {
                            FoodID = 7,
                            FoodDescription = "Mollitia cum ad et itaque.",
                            FoodName = "Cardboard Pizza",
                            FoodType = "Burger",
                            VendorID = 2
                        },
                        new
                        {
                            FoodID = 8,
                            FoodDescription = "Nihil velit voluptas laudantium sunt velit.",
                            FoodName = "A Warm Apple pie",
                            FoodType = "Muffin",
                            VendorID = 2
                        },
                        new
                        {
                            FoodID = 9,
                            FoodDescription = "Esse quos enim natus.",
                            FoodName = "Cardboard Pizza",
                            FoodType = "Snack",
                            VendorID = 2
                        });
                });

            modelBuilder.Entity("Backend.Models.Furniture", b =>
                {
                    b.Property<int>("furnitureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("furnitureID"), 1L, 1);

                    b.Property<int>("VendorID")
                        .HasColumnType("int");

                    b.Property<string>("furnitureDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("furnitureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("furnitureType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("furnitureID");

                    b.ToTable("Furniture");

                    b.HasData(
                        new
                        {
                            furnitureID = 2804,
                            VendorID = 2,
                            furnitureDescription = "Ut aut quis iure a impedit fugiat dolorum.",
                            furnitureName = "Leather couch 3000",
                            furnitureType = "Bed"
                        },
                        new
                        {
                            furnitureID = 3198,
                            VendorID = 1,
                            furnitureDescription = "Tempore quo quod adipisci unde.",
                            furnitureName = "The Pull Out",
                            furnitureType = "Couch"
                        },
                        new
                        {
                            furnitureID = 2511,
                            VendorID = 1,
                            furnitureDescription = "Voluptatibus unde molestiae non ea possimus fugiat ut.",
                            furnitureName = "Leather couch 3000",
                            furnitureType = "Occasional Furniture"
                        });
                });

            modelBuilder.Entity("Backend.Models.Vehicles", b =>
                {
                    b.Property<int>("vehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vehicleID"), 1L, 1);

                    b.Property<int>("VendorID")
                        .HasColumnType("int");

                    b.Property<string>("vehicleDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vehicleID");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            vehicleID = 64406,
                            VendorID = 1,
                            vehicleDescription = "Tempore accusantium fugit. Est soluta rerum sapiente sint laudantium voluptatem ut. Consequatur minima quod sequi commodi quos magnam at voluptatum earum. Consequatur beatae dignissimos quas.",
                            vehicleName = "Honda Civic",
                            vehicleType = "StationWagon"
                        },
                        new
                        {
                            vehicleID = 78582,
                            VendorID = 2,
                            vehicleDescription = "Consequatur quo facere quidem provident. Nulla consequuntur voluptatum. Tenetur ut et excepturi dignissimos corporis officiis. Repellat autem eligendi nihil sint vero eum ad.",
                            vehicleName = "Holden Crewman  S",
                            vehicleType = "Shitbox"
                        },
                        new
                        {
                            vehicleID = 59003,
                            VendorID = 2,
                            vehicleDescription = "Alias eius quam est cupiditate eos expedita ipsum cum error. Sit impedit saepe similique ut et. Incidunt ipsam perspiciatis rerum aliquid sequi eveniet doloremque. Minus nihil nisi consequatur. Omnis nihil sapiente vel cupiditate facilis dignissimos numquam deserunt dolorem.",
                            vehicleName = "Nissan Cefiro",
                            vehicleType = "Shitbox"
                        },
                        new
                        {
                            vehicleID = 77085,
                            VendorID = 2,
                            vehicleDescription = "Perferendis magnam fugiat quia aliquid maxime odit asperiores accusantium nostrum. Facere sapiente quaerat sunt unde corrupti veritatis. Sapiente debitis qui. Quibusdam et harum omnis eaque. Aperiam exercitationem est. Qui omnis suscipit unde.",
                            vehicleName = "Honda Civic",
                            vehicleType = "Shitbox"
                        });
                });

            modelBuilder.Entity("Backend.Models.Vendor", b =>
                {
                    b.Property<int>("VendorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendorID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehiclesvehicleID")
                        .HasColumnType("int");

                    b.HasKey("VendorID");

                    b.HasIndex("VehiclesvehicleID");

                    b.ToTable("Vendor");

                    b.HasData(
                        new
                        {
                            VendorID = 1,
                            Description = "Animi velit at voluptatum expedita nisi itaque et ducimus nulla.",
                            Location = "92145 Devonte Rapids",
                            Name = "Procrastination Solutions"
                        },
                        new
                        {
                            VendorID = 2,
                            Description = "Neque quia sit.",
                            Location = "932 Clark Summit",
                            Name = "Efficiency Experts Inc. (Don't Hold Your Breath)"
                        });
                });

            modelBuilder.Entity("Backend.Models.Vendor", b =>
                {
                    b.HasOne("Backend.Models.Vehicles", null)
                        .WithMany("Vendors")
                        .HasForeignKey("VehiclesvehicleID");
                });

            modelBuilder.Entity("Backend.Models.Vehicles", b =>
                {
                    b.Navigation("Vendors");
                });
#pragma warning restore 612, 618
        }
    }
}
